import { VerticalBox } from "std-widgets.slint";
import "../font/Roboto-Regular.ttf";

export component LiplDisplay inherits Window {
    title: "Lipl Display";
    default-font-family: "Roboto";
    background: dark ? black : white;
    preferred-width: 640px;
    preferred-height: 480px;

    in property<bool> dark: false;
    in property<string> part: "";
    in property<string> status: "";
    in-out property<int> fontsize: 40;

    VerticalBox {
        padding-left: 20px;
        padding-right: 20px;
        padding-top: 20px;
        padding-bottom: 20px;

        HorizontalLayout {
            alignment: center;

            VerticalBox {
                part:= Text {
                    color: root.dark ? white : black;
                    font-size: root.fontsize * 1px;
                    text: "\{root.part}";
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }

                status:= Text {
                    color: root.dark ? white : black;
                    font-size: root.fontsize * 0.8 * 1px;
                    text: "\{root.status}";
                    height: 5%;
                    horizontal-alignment: left;
                }
            }
        }
    }
}
