name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: install ubuntu dependencies
        run: sudo apt update && sudo apt install libdbus-1-dev libudev-dev libgbm-dev libxkbcommon-dev libfontconfig1-dev libseat-dev libsystemd-dev libinput-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy,rustfmt
      - uses: actions/checkout@v7
      - name: formatting
        run: cargo fmt --all -- --check
      - name: clippy slint version
        run: cargo clippy -- --no-deps -D warnings
      - name: build slint version
        run: cargo build --release
